## Import Lib

In [102]:
import pandas as pd
import numpy as np
import math
import re

## Import Data

In [103]:
url_penduduk = "https://raw.githubusercontent.com/Rashifalmas/Datathon2026/refs/heads/main/data/data_penduduk_2023.csv"
url_rs = "https://raw.githubusercontent.com/Rashifalmas/Datathon2026/refs/heads/main/data/data_rs_2026.csv"

df1 = pd.read_csv(url_penduduk)
df2 = pd.read_csv(url_rs)

## Benerin Data Penduduk

In [104]:
df1.head()

,Kab/Kota,0-4,5-9,10-14,15-19,20-24,25-29,30-34,35-39,40-44,45-49,50-54,55-59,60-64,65-69,70-74,75+,TOTAL
0,Kep Seribu,2736,2565,2324,2381,2642,2491,2328,2199,1976,1790,1581,1312,971,611,339,277,28523
1,Jakarta Selatan,148917,159195,164800,171467,175884,175765,174088,175155,176447,176215,158423,131307,100061,69421,41752,36709,2235606
2,Jakarta Timur,223688,234365,236113,241086,243352,243200,245030,246610,241768,231322,203846,169169,130976,93144,55257,40692,3079618
3,Jakarta Pusat,65357,71568,74163,79049,83265,82275,82584,82824,79924,78251,73410,64676,51283,36906,22990,20789,1049314
4,Jakarta Barat,177478,184543,188331,189332,189563,191611,200745,208376,202432,186830,159684,132196,103077,73516,44941,37399,2470054

In [105]:
## Ga perlu Kepulauan Seribu
df1 = df1[df1['Kab/Kota'] != 'Kep Seribu']
df1.head()

,Kab/Kota,0-4,5-9,10-14,15-19,20-24,25-29,30-34,35-39,40-44,45-49,50-54,55-59,60-64,65-69,70-74,75+,TOTAL
1,Jakarta Selatan,148917,159195,164800,171467,175884,175765,174088,175155,176447,176215,158423,131307,100061,69421,41752,36709,2235606
2,Jakarta Timur,223688,234365,236113,241086,243352,243200,245030,246610,241768,231322,203846,169169,130976,93144,55257,40692,3079618
3,Jakarta Pusat,65357,71568,74163,79049,83265,82275,82584,82824,79924,78251,73410,64676,51283,36906,22990,20789,1049314
4,Jakarta Barat,177478,184543,188331,189332,189563,191611,200745,208376,202432,186830,159684,132196,103077,73516,44941,37399,2470054
5,Jakarta Utara,136561,141672,140507,138687,138863,141993,148164,151862,147368,135711,113414,92188,72175,52782,31813,25225,1808985

In [106]:
## Satuin kolom 0-4, 5-9, 10-14, 15-19 = Anak_Remaja
df1['Total_Anak_Remaja'] = df1['0-4'] + df1['5-9'] + df1['10-14'] + df1['15-19']

## Satuin kolom 20-24, 25-29, 30-34, 35-39, 40-44, 45-49 = Dewasa
df1['Total_Dewasa'] = df1['20-24'] + df1['25-29'] + df1['30-34'] + df1['35-39'] + df1['40-44'] + df1['45-49']

## Satuin kolom 50-54, 55-59, 60-64, 65-69, 70-74, 75+ = Lansia
df1['Total_Lansia'] = df1['50-54'] + df1['55-59'] + df1['60-64'] + df1['65-69'] + df1['70-74'] + df1['75+']

df1.head()

,Kab/Kota,0-4,5-9,10-14,15-19,20-24,25-29,30-34,35-39,40-44,...,50-54,55-59,60-64,65-69,70-74,75+,TOTAL,Total_Anak_Remaja,Total_Dewasa,Total_Lansia
1,Jakarta Selatan,148917,159195,164800,171467,175884,175765,174088,175155,176447,...,158423,131307,100061,69421,41752,36709,2235606,644379,1053554,537673
2,Jakarta Timur,223688,234365,236113,241086,243352,243200,245030,246610,241768,...,203846,169169,130976,93144,55257,40692,3079618,935252,1451282,693084
3,Jakarta Pusat,65357,71568,74163,79049,83265,82275,82584,82824,79924,...,73410,64676,51283,36906,22990,20789,1049314,290137,489123,270054
4,Jakarta Barat,177478,184543,188331,189332,189563,191611,200745,208376,202432,...,159684,132196,103077,73516,44941,37399,2470054,739684,1179557,550813
5,Jakarta Utara,136561,141672,140507,138687,138863,141993,148164,151862,147368,...,113414,92188,72175,52782,31813,25225,1808985,557427,863961,387597

In [107]:
# Estimasi resiko MRI per bulan
# Anak/Remaja (0-19) : 0.02% (0.0002)
# Dewasa (20-49)     : 0.1% (0.001)
# Lansia (50+)       : 0.5%  (0.005)

df1['Estimasi_Pasien_Bulan'] = (
    (df1['Total_Anak_Remaja'] * 0.0002) +
    (df1['Total_Dewasa'] * 0.001) +
    (df1['Total_Lansia'] * 0.005)
)

df1.head()

,Kab/Kota,0-4,5-9,10-14,15-19,20-24,25-29,30-34,35-39,40-44,...,55-59,60-64,65-69,70-74,75+,TOTAL,Total_Anak_Remaja,Total_Dewasa,Total_Lansia,Estimasi_Pasien_Bulan
1,Jakarta Selatan,148917,159195,164800,171467,175884,175765,174088,175155,176447,...,131307,100061,69421,41752,36709,2235606,644379,1053554,537673,3870.7948
2,Jakarta Timur,223688,234365,236113,241086,243352,243200,245030,246610,241768,...,169169,130976,93144,55257,40692,3079618,935252,1451282,693084,5103.7524
3,Jakarta Pusat,65357,71568,74163,79049,83265,82275,82584,82824,79924,...,64676,51283,36906,22990,20789,1049314,290137,489123,270054,1897.4204
4,Jakarta Barat,177478,184543,188331,189332,189563,191611,200745,208376,202432,...,132196,103077,73516,44941,37399,2470054,739684,1179557,550813,4081.5588
5,Jakarta Utara,136561,141672,140507,138687,138863,141993,148164,151862,147368,...,92188,72175,52782,31813,25225,1808985,557427,863961,387597,2913.4314

In [108]:
# Ubah bulanan jadi harian (dibagi 30 hari)
# Pembulatan pake numpy
# Konversi integer
df1['Estimasi_Pasien_Hari'] = np.ceil(df1['Estimasi_Pasien_Bulan'] / 30).astype(int)

In [109]:
## Simpen ke variable baru & pilih kolom fix biar gampang
df1_prototipe = df1[['Kab/Kota', 'Total_Anak_Remaja', 'Total_Dewasa', 'Total_Lansia', 'Estimasi_Pasien_Bulan', 'Estimasi_Pasien_Hari']]

df1_prototipe.head()

,Kab/Kota,Total_Anak_Remaja,Total_Dewasa,Total_Lansia,Estimasi_Pasien_Bulan,Estimasi_Pasien_Hari
1,Jakarta Selatan,644379,1053554,537673,3870.7948,130
2,Jakarta Timur,935252,1451282,693084,5103.7524,171
3,Jakarta Pusat,290137,489123,270054,1897.4204,64
4,Jakarta Barat,739684,1179557,550813,4081.5588,137
5,Jakarta Utara,557427,863961,387597,2913.4314,98

## Benerin Data RS

In [110]:
df2.head()

,Unit Eksekusi Diagnostik Institusi Medis Rumah Sakit Tersier dan Kuartener,Kuadran Yurisdiksi Wilayah Kota Administrasi,Rentang Batas Volume Maksimal Eksekusi Throughput Pemindaian Per Harian Pasien,Titik Elevasi Sumbu Garis Lintang (Latitude / Paralel Selatan Absolut Geospasial),Titik Resolusi Elevasi Sumbu Garis Bujur (Longitude / Meridian Timur Absolut Spasial)
0,RSUPN Dr. Cipto Mangunkusumo (RSCM) (Multi-Mes...,Jakarta Pusat,60 - 80,-61.972.417,1.068.467.866
1,RSPAD Gatot Soebroto (Tipe A Militer),Jakarta Pusat,40 - 55,-6.18333*,106.83333*
2,RS Islam Jakarta Cempaka Putih,Jakarta Pusat,25 - 35,-61.762.000,1.068.680.000
3,Siloam Hospitals Agora (Pusat Trauma),Jakarta Pusat,30 - 35,-6.17620*,106.86800*
4,Primaya Hospital PGI Cikini,Jakarta Pusat,20 - 30,-6.18333*,106.83333*

In [111]:
## Sederhanakan kolom
df2 = df2.rename(columns={
    df2.columns[0]: 'Nama_RS',
    df2.columns[1]: 'Wilayah',
    df2.columns[2]: 'Kapasitas_Range',
    df2.columns[3]: 'Latitude',
    df2.columns[4]: 'Longitude'
})

df2.head()

,Nama_RS,Wilayah,Kapasitas_Range,Latitude,Longitude
0,RSUPN Dr. Cipto Mangunkusumo (RSCM) (Multi-Mes...,Jakarta Pusat,60 - 80,-61.972.417,1.068.467.866
1,RSPAD Gatot Soebroto (Tipe A Militer),Jakarta Pusat,40 - 55,-6.18333*,106.83333*
2,RS Islam Jakarta Cempaka Putih,Jakarta Pusat,25 - 35,-61.762.000,1.068.680.000
3,Siloam Hospitals Agora (Pusat Trauma),Jakarta Pusat,30 - 35,-6.17620*,106.86800*
4,Primaya Hospital PGI Cikini,Jakarta Pusat,20 - 30,-6.18333*,106.83333*

In [112]:
## Benerin kordinat
def bersihkan_koordinat(teks):
    teks = str(teks).replace('*', '').strip()
    teks = teks.replace('.', '')

    try:
        angka = float(teks)
        if angka < -100:
            angka = angka / (10 ** (len(str(int(abs(angka)))) - 1))
        elif angka > 1000:
            angka = angka / (10 ** (len(str(int(angka))) - 3))
        return angka
    except ValueError:
        return None

df2['Latitude'] = df2['Latitude'].apply(bersihkan_koordinat)
df2['Longitude'] = df2['Longitude'].apply(bersihkan_koordinat)

In [113]:
## Benerin kapasitas jadi batas atas
def ekstrak_kapasitas(teks):
    if pd.isna(teks): return 0
    angka = re.findall(r'\d+', str(teks))
    return int(angka[-1]) if angka else 0

df2['Kapasitas_Harian'] = df2['Kapasitas_Range'].apply(ekstrak_kapasitas)

In [114]:
## Simpen ke variable baru & pilih kolom fix biar gampang
df_rs_bersih = df2[['Nama_RS', 'Wilayah', 'Kapasitas_Harian', 'Latitude', 'Longitude']]
df_rs_bersih.head()

,Nama_RS,Wilayah,Kapasitas_Harian,Latitude,Longitude
0,RSUPN Dr. Cipto Mangunkusumo (RSCM) (Multi-Mes...,Jakarta Pusat,80,-6.197242,106.846787
1,RSPAD Gatot Soebroto (Tipe A Militer),Jakarta Pusat,55,-6.183330,106.833330
2,RS Islam Jakarta Cempaka Putih,Jakarta Pusat,35,-6.176200,106.868000
3,Siloam Hospitals Agora (Pusat Trauma),Jakarta Pusat,35,-6.176200,106.868000
4,Primaya Hospital PGI Cikini,Jakarta Pusat,30,-6.183330,106.833330

## Load Balancing

In [115]:
df1_prototipe = df1_prototipe[df1_prototipe['Kab/Kota'] != 'DKI Jakarta'].copy()
df1_prototipe = df1_prototipe.reset_index(drop=True)

## Bikin titik tengah per wilayah buat patokan menuju RS
koordinat_jakarta = {
    'Jakarta Selatan': (-6.2615, 106.8106),
    'Jakarta Timur': (-6.2250, 106.9004),
    'Jakarta Pusat': (-6.1805, 106.8284),
    'Jakarta Barat': (-6.1683, 106.7588),
    'Jakarta Utara': (-6.1214, 106.8966)
}

df1_prototipe['Lat_Kota'] = df1_prototipe['Kab/Kota'].map(lambda x: koordinat_jakarta[x][0])
df1_prototipe['Lon_Kota'] = df1_prototipe['Kab/Kota'].map(lambda x: koordinat_jakarta[x][1])

df1_prototipe.head()

,Kab/Kota,Total_Anak_Remaja,Total_Dewasa,Total_Lansia,Estimasi_Pasien_Bulan,Estimasi_Pasien_Hari,Lat_Kota,Lon_Kota
0,Jakarta Selatan,644379,1053554,537673,3870.7948,130,-6.2615,106.8106
1,Jakarta Timur,935252,1451282,693084,5103.7524,171,-6.2250,106.9004
2,Jakarta Pusat,290137,489123,270054,1897.4204,64,-6.1805,106.8284
3,Jakarta Barat,739684,1179557,550813,4081.5588,137,-6.1683,106.7588
4,Jakarta Utara,557427,863961,387597,2913.4314,98,-6.1214,106.8966

In [116]:
## Bikin fungsi buat ngitung jarak (sementara sebelum pake azure maps)
def hitung_jarak(lat1, lon1, lat2, lon2):
    # Rumus Haversine untuk jarak di bumi (dalam KM)
    R = 6371.0
    dlat = math.radians(lat2 - lat1)
    dlon = math.radians(lon2 - lon1)
    a = math.sin(dlat / 2)**2 + math.cos(math.radians(lat1)) * math.cos(math.radians(lat2)) * math.sin(dlon / 2)**2
    c = 2 * math.atan2(math.sqrt(a), math.sqrt(1 - a))
    return R * c

In [117]:
## PERSIAPAN DATA
df_rs = df_rs_bersih.copy()

## ALOKASI TAHAP 1 (PROPORSIONAL PER KOTA)
df_rs['Beban_Awal'] = 0
for index, row in df1_prototipe.iterrows():
    kota = row['Kab/Kota']
    pasien_masuk = row['Estimasi_Pasien_Hari']

    # Cari RS di kota tersebut
    rs_di_kota = df_rs[df_rs['Wilayah'] == kota]
    if not rs_di_kota.empty:
        total_kapasitas_kota = rs_di_kota['Kapasitas_Harian'].sum()
        # Bagi proporsional
        for i, rs in rs_di_kota.iterrows():
            rasio = rs['Kapasitas_Harian'] / total_kapasitas_kota
            df_rs.at[i, 'Beban_Awal'] = int(np.ceil(pasien_masuk * rasio))

## DETEKSI OVERFLOW & SISA KAPASITAS
df_rs['Overflow'] = df_rs['Beban_Awal'] - df_rs['Kapasitas_Harian']
df_rs['Overflow'] = df_rs['Overflow'].apply(lambda x: x if x > 0 else 0)

df_rs['Sisa_Kapasitas'] = df_rs['Kapasitas_Harian'] - df_rs['Beban_Awal']
df_rs['Sisa_Kapasitas'] = df_rs['Sisa_Kapasitas'].apply(lambda x: x if x > 0 else 0)

## REDISTRIBUSI (LOAD BALANCING LINTAS KOTA)
print("=== LOG REDISTRIBUSI PASIEN OVERLOAD ===")
for index, rs_over in df_rs[df_rs['Overflow'] > 0].iterrows():
    pasien_telantar = rs_over['Overflow']

    while pasien_telantar > 0:
        # Cari RS yang masih punya Sisa Kapasitas
        rs_tersedia = df_rs[df_rs['Sisa_Kapasitas'] > 0].copy()

        if rs_tersedia.empty:
            print(f"CRITICAL WARNING: Seluruh RS di Jakarta Penuh! {pasien_telantar} pasien dari {rs_over['Nama_RS']} tidak tertangani.")
            break

        # Hitung jarak dari RS Overload ke RS yang tersedia
        rs_tersedia['Jarak'] = rs_tersedia.apply(lambda row: hitung_jarak(rs_over['Latitude'], rs_over['Longitude'], row['Latitude'], row['Longitude']), axis=1)

        # Urutkan berdasarkan jarak terdekat
        rs_terdekat = rs_tersedia.sort_values('Jarak').iloc
        id_terdekat = rs_terdekat.name

        # Pindahkan pasien
        kapasitas_diterima = min(pasien_telantar, rs_terdekat['Sisa_Kapasitas'])
        pasien_telantar -= kapasitas_diterima

        # Update tabel
        df_rs.at[id_terdekat, 'Sisa_Kapasitas'] -= kapasitas_diterima
        df_rs.at[id_terdekat, 'Beban_Awal'] += kapasitas_diterima # Tambah beban ke RS tujuan
        df_rs.at[index, 'Overflow'] = pasien_telantar # Kurangi overflow di RS asal
        df_rs.at[index, 'Beban_Awal'] -= kapasitas_diterima # Pindahkan dari beban RS awal

        print(f"[*] {kapasitas_diterima} Pasien dari {rs_over['Nama_RS']} ({rs_over['Wilayah']}) dialihkan ke {rs_terdekat['Nama_RS']} ({rs_terdekat['Wilayah']}) - Jarak: {rs_terdekat['Jarak']:.2f} km")

print("\n=== HASIL AKHIR SETELAH LOAD BALANCING ===")
# Menampilkan RS yang kapasitasnya terisi penuh
print(df_rs[['Nama_RS', 'Wilayah', 'Kapasitas_Harian', 'Beban_Awal', 'Sisa_Kapasitas']].sort_values('Beban_Awal', ascending=False).head(10))

=== LOG REDISTRIBUSI PASIEN OVERLOAD ===

=== HASIL AKHIR SETELAH LOAD BALANCING ===
                                              Nama_RS        Wilayah  \
38  RS Pusat Otak Nasional (RSPON) Prof. Dr. dr. M...  Jakarta Timur
39       RSUP Persahabatan (Respirasi Jantung Kanker)  Jakarta Timur
40  Premier Jatinegara Hospital (Fusi Intervensi O...  Jakarta Timur
23         Pusat Kanker Nasional Rumah Sakit Dharmais  Jakarta Barat
41              RS EMC Pulomas (Bedah 24 Jam Darurat)  Jakarta Timur
42                     Columbia Asia Hospital Pulomas  Jakarta Timur
25  Siloam Hospitals Kebon Jeruk (Pusat Trauma Saraf)  Jakarta Barat
21  Mandaya Royal Hospital Puri (Award Bedah Saraf...  Jakarta Barat
22  RSJPD Harapan Kita (Pusat Kardiovaskular Nasio...  Jakarta Barat
28  Tzu Chi Hospital PIK (Revolusi Ganda AI 1.5T d...  Jakarta Utara

    Kapasitas_Harian  Beban_Awal  Sisa_Kapasitas
38                75          42              33
39                60          34              26
40                55          31              24
23                65          28              37
41                45          25              20
42                40          23              17
25                50          22              28
21                50          22              28
22                50          22              28
28                95          22              73